app-sre/go-qontract-reconcile

README.md
pkg/qontract_client.go
pkg/qontract_client_test.go
pkg/vault.go
pkg/vault_test.go

Add client timeout for Qontract Http Client

Qontract client HTTP timeout

---

README.md
pkg/qontract_client.go
pkg/qontract_client_test.go

Make it possible to configure Basic Auth headers for Qontract Client

Add basic auth to Qontract

---

example.yml
go.mod
go.sum
pkg/vault.go

Using approle helper module for signing in to Vault using approle

Fix approle login

---

cmd/user_validator.go
pkg/reconcile.go
pkg/reconcile_test.go

Make sure ValidationRunner exists with code >0 in case of any error during run of validations

Ensure Error exit status

---

README.md
internal/user_validator.go
internal/user_validator_test.go

A workaround to ignore keys that are already invalid.

Add allow list for invalid keys

---

pkg/gql/qontract_client.go
pkg/gql/qontract_client_test.go

Adding retries on failed requests to GraphQL.
Using hashicorp go-retryablehttp, since it got all we need.
Implemented by adding wrapper types retryableHttpWrapper and zapLog, which
support the interface required by graphql

GQL add retries

---

pkg/github.go

Falsly used Enterprise github method, should however just update the BaseURL after creating the client. Also added some code to make sure, we have a trailing slash

Fix github mirror

---

internal/account_notifier.go
internal/account_notifier_test.go
openshift/deployment-template.yml
pkg/gql/qontract_client.go
pkg/gql/qontract_client_test.go
pkg/vault.go
pkg/vault_test.go

This aligns the integration configuration with the configuration used in https://github.com/app-sre/qontract-reconcile
It also adds a template that can be used to deploy integrations using a saas file
https://issues.redhat.com/browse/APPSRE-6816

Align configuration with qontract-reconcile

---

openshift/deployment-template.yml

Set component compatible with current deployment

Fix component

---

pkg/reconcile.go

Make statement debug, cause it's spamming the logs

Remove debug statement

---

internal/account_notifier.go
pkg/gql/qontract_client.go
pkg/util/util.go

Suppressing Stack traces in MR builds and getting info on reencryption.
[APPSRE-6816](https://issues.redhat.com/browse/APPSRE-6816)

Fix logging

---

internal/account_notifier.go

Fix typo in email template
Align vault path with qontract-reconcile

Small fixes

---

Dockerfile

Adding git installtion

---

pkg/reconcile/integration.go
pkg/reconcile/integration_test.go
pkg/reconcile/reconcile.go
pkg/reconcile/validation.go
pkg/reconcile/validation_test.go

No ticket exists for this change. The majority of this PR is moving code around, splitting up reconcile.go. 
Additionally, it is adding unleash integration to the IntegrationRunner.
Tested this locally.

Minor fixes

---

Makefile
cmd/account_notifier.go
cmd/root.go
internal/accountnotifier/account_notifier.go
internal/accountnotifier/account_notifier_test.go
internal/example/generate.go
internal/gitpartitionsync/producer/encrypt.go
internal/gitpartitionsync/producer/gitlab.go
internal/gitpartitionsync/producer/producer.go
internal/gitpartitionsync/producer/producer_test.go
internal/gitpartitionsync/producer/s3.go
internal/gitpartitionsync/producer/tar.go
internal/uservalidator/user_validator.go
main.go
pkg/aws/awsclient.go
pkg/aws/credentials.go
pkg/github/github.go
pkg/gql/qontract_client.go
pkg/gql/qontract_client_test.go
pkg/pgp/pgp.go
pkg/state/state.go
pkg/unleash/unleash.go
pkg/unleash/unleash_api.go
pkg/unleash/unleash_test.go
pkg/util/util.go
pkg/vault/vault.go
pr_check.sh

Applying lint recommendations where it makes sense.
Also adding linting to PR pipeline
https://issues.redhat.com/browse/APPSRE-7234

Add liniting

---

openshift/deployment-git-partition-sync-producer.yml
openshift/deployment-template.yml

Add missing resources config for `internal-certificates`

Add resources config for internal-certificates

---

openshift/deployment-git-partition-sync-producer.yml
openshift/deployment-template.yml

Part of [APPSRE-8174](https://issues.redhat.com/browse/APPSRE-8174), unset cpu limits to avoid cpu throttle.

Unset CPU limits

---

Dockerfile

As required by enterprise contract checks.

Copy licenses to final image

---

hack/update_schema.sh

https://issues.redhat.com/browse/APPSRE-11018

use official build of qontract-validator

---

hack/update_schema.sh
internal/accountnotifier/account_notifier_test.go
internal/accountnotifier/generate.go
internal/accountnotifier/generated.go
internal/example/generate.go
internal/example/generated.go
internal/uservalidator/generate.go
internal/uservalidator/generated.go
schema.graphql

* JIRA: [APPSRE-11644](https://issues.redhat.com/browse/APPSRE-11644)
* Related to https://github.com/app-sre/qontract-reconcile/pull/4992

Remove slack-username
